### ISSUE TITLE
Do not stop playback on minimize

### ISSUE THREAD

**Issue by smyru** [tworaz/sailfish-ytplayer#21] opened 2015-02-13 20:44 UTC
I would like to request a small change not to stop playing when app is minimized or an option to disable it.

Currently player will pause playback when it is being minimized. This is quite legimitate for a video use case, but quite the contrary when user listens to a Youtube hosted or downloaded music. 

Consider such use case: user has loaded downloaded clip, and wants to listen to it. It starts playing, app is minimized to do other tasks and it directly stops playing. Additional action is needed on the cover to start playing again.

**Comment by tworaz** [comment] 2015-02-16 21:35
Hi, and thank you for reporting th issue. I've seen the same request being made a few times in the comment section in harbour. I do plan to add an option to customize pausing behaviour in 0.5.0 release. The problem is I don't know when this will be. I currently don't have any free time to spent on YTPlayer. Unfortunately I have a full time job that also involves coding. It's hard to come home after writing code for 10h and do it again.

**Comment by tworaz** [comment] 2015-09-15 19:57
On master the behaviour can be customized via newly added player settings page. The feature will be released in 0.5.0.

**Closed by tworaz** 2015-09-15 19:57 UTC
