### ISSUE TITLE
Can't watch copyrighted videos after 0.4.1

### ISSUE THREAD

**Issue by Kuivahuikka** [tworaz/sailfish-ytplayer#17] opened 2015-01-23 14:18 UTC
When I try to watch a video with copyrighted music, It says :  "YTPlayer failed to find usable video streams". It was possible to watch copyrighted videos before the update.

**Comment by tworaz** [comment] 2015-01-26 19:41
Thanks for reporting the issue.

Since 0.4.1 links to copyrighted videos are obtained through youtube-dl script. The original solution from 0.3.0 no longer worked since YTAPI.com started requiring monthly subsription fee.

It's possible that for some reason the script is not able to obtain the links from your location. Could you try to reproduce the problem and go to Settings->Logs to see if there is anything interesting there. I'd look for lines starting with "YouTubeDL subprocess." Afeter that one you should see something like "youtube-dl process finished, status: 0, exit code: 0". If you see anything else could you take a screenshot and post it somewhere?

**Comment by tworaz** [comment] 2015-09-15 19:58
Closing due to lack of any additional info regarding the problem. Please re-open if you still have problems in 0.5.0.

**Closed by tworaz** 2015-09-15 19:58 UTC
